#!/bin/bash
# Fresh install - Set up a fresh arch-based install

ROOT_UID=0    # Only users with $UID 0 have root privileges
E_NOTROOT=87  # Non-root exit error
ORIG_DIR=$PWD # If user wants to return to original working directory

ALIASES=\
"\n\
alias search='pacman -Ss'\n\
alias searchy='yay -Ss'\n\
alias remove='sudo pacman -Rs'\n\
alias update='sudo pacman -Syu'\n\
alias ls='lsd'"

cd $HOME

echo "Creating aliases..."

if [ "$SHELL" == "/bin/bash" ]
then
	echo -e ${ALIASES} >> .bashrc
elif [ "$SHELL" == "/bin/zsh" ]
then
	echo -e ${ALIASES} >> .zshrc
else
	echo "Can't create aliases."
	echo "Current shell: $SHELL"
	echo "Supported shells: bash, zsh"
	exit 1
fi

# Install packages
# Official repositories:
#	[
#		-base-devel
#		-bat
#		-cmatrix
#		-code
#		-discord
#		-expect
#		-ffmpeg
#		-gcc
#		-git
#		-htop
#		-libreoffice-fresh
#		-lsd
#		-neofetch
#		-ocl-icd
#		-okular
#		-pacgraph
#		-transmission-gtk
#		-virtualbox
#		-vlc
#		-xclip
#		-yay
#	]
# AUR:
#	[
#		-google-chrome
#	]

echo "Updating..."

sudo pacman -Syu

echo "Installing packages..."

# Official repositories
# NOTE: VIRTUALBOX VERSION DEPENDS ON KERNEL.
printf "\nKERNEL: %s\n" $(uname -r)

sudo pacman -S virtualbox
modprobe vboxdrv

sudo pacman -S --noconfirm --needed \
                 base-devel bat cmatrix code discord expect \
                 ffmpeg gcc git htop libreoffice-fresh lsd neofetch \
				 ocl-icd okular pacgraph transmission-gtk vlc xclip yay \
                 
# VS Code extensions
code --install-extension tuttieee.emacs-mcx
code --install-extension CoenraadS.bracket-pair-colorizer-2
code --install-extension eamodio.gitlens
code --install-extension ms-python.python
code --install-extension ritwickdey.LiveServer
code --install-extension wayou.vscode-todo-highlight

# TODO: Find --noconfirm equivalent for yay
# AUR
yay -S google-chrome

# TODO: Move script to /usr/local/bin, execute,
#+      then self-destruct.

echo $ORIG_DIR

exec $SHELL
