#!/bin/bash
# Fresh install - Set up a fresh arch-based install

ROOT_UID=0    # Only users with $UID 0 have root privileges
E_NOTROOT=87  # Non-root exit error
ORIG_DIR=$PWD # If user wants to return to original working directory

ALIASES=\
"\n\
alias search='pacman -Ss'\n\
alias searchy='yay -Ss'\n\
alias remove='sudo pacman -Rs'\n\
alias update='sudo pacman -Syu'"

cd $HOME

echo "Creating aliases..."

if [ "$SHELL" == "/bin/bash" ]
then
	echo -e ${ALIASES} >> .bashrc
elif [ "$SHELL" == "/bin/zsh" ]
then
	echo -e ${ALIASES} >> .zshrc
else
	echo "Can't create aliases."
	echo "Current shell: $SHELL"
	echo "Supported shells: bash, zsh"
	exit 1
fi

# Install packages
# Official repositories:
#	[
#		-base-devel
#		-code
#		-ffmpeg
#		-git
#		-neofetch
#		-transmission-gtk
#		-vlc
#		-xclip
#		-yay
#	]
# AUR:
#	[
#		-atom
#		-google-chrome
#	]
# Atom Package Manager:
# [
#		-atom-beautify
#		-emacs-plus
#		-livereload
#		-minimap
#		-pigments
#		-todo-show
# ]

echo "Installing packages..."

# Official repositories
# NOTE: VIRTUALBOX VERSION DEPENDS ON KERNEL.
printf "\nKERNEL: %s\n" $(uname -r)

sudo pacman -Syu virtualbox
modprobe vboxdrv

sudo pacman -S --noconfirm --needed \
                 base-devel code ffmpeg git neofetch \
                 transmission-gtk vlc xclip yay

# AUR
yay -S atom google-chrome

# APM
apm install atom-beautify emacs-plus livereload minimap \
            pigments todo-show

# TODO: Move script to /usr/local/bin,
#+      then self-destruct.

echo $ORIG_DIR

exec $SHELL
